[build]
  command = "npm run build"
  publish = ".next"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[[redirects]]
  from = "/pages/about"
  to = "https://www.google.com/search?q=anything"
  status = 301
  force = true
  headers = {X-From = "Netlify"}