[build]
  command = "npm run build"
  publish = ".next"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[[redirects]]
  from = "www.saltspell.io/about"
  to = "/https://www.google.com/search?q=anything"
  status = 301
  force = true